export const SET_MATRICE = 'SET_MATRICE'
export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'

export const SELECT_GRID_NUMBER = 'SELECT_GRID_NUMBER'
export const SELECT_STAR_NUMBER = 'SELECT_STAR_NUMBER'